version: '3.8'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UUID: ${UUID}
        GUID: ${GUID}
    image: drupal:10.4-php8.3-apache-bookworm
    container_name: drupal-qa-testing
    ports:
      - "8083:80"  # Using port 8083 for Drupal on host and 80 inside container
    volumes:
      - ./drupal:/opt/drupal
      - ./optinclude:/opt/include # Mounting optinclude directory
      - ./tests:/opt/tests        # Mounting tests directory
      - ./playwright.config.js:/opt/playwright.config.js  # Mapping config file
      - ./test-results:/opt/test-results  # Mounting test results directory
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
    depends_on:
      - db
    command: ["/bin/sh", "-c", ". /opt/include/compinstall.sh && apache2-foreground"]

  db:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3310:3306"  # Using port 3310 for MariaDB
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8085:80"  # Using port 8085 for PHPMyAdmin
    environment:
      - PMA_HOST=db
      - PMA_USER=drupal
      - PMA_PASSWORD=drupal
    depends_on:
      - db

volumes:
  db_data:
